// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gpbrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtocolMessage struct {
	CmdId                uint64   `protobuf:"varint,1,opt,name=CmdId,proto3" json:"CmdId,omitempty"`
	CmdSeq               uint64   `protobuf:"varint,2,opt,name=CmdSeq,proto3" json:"CmdSeq,omitempty"`
	CmdData              []byte   `protobuf:"bytes,3,opt,name=CmdData,proto3" json:"CmdData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolMessage) Reset()         { *m = ProtocolMessage{} }
func (m *ProtocolMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage) ProtoMessage()    {}
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ProtocolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolMessage.Unmarshal(m, b)
}
func (m *ProtocolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolMessage.Marshal(b, m, deterministic)
}
func (m *ProtocolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolMessage.Merge(m, src)
}
func (m *ProtocolMessage) XXX_Size() int {
	return xxx_messageInfo_ProtocolMessage.Size(m)
}
func (m *ProtocolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolMessage proto.InternalMessageInfo

func (m *ProtocolMessage) GetCmdId() uint64 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *ProtocolMessage) GetCmdSeq() uint64 {
	if m != nil {
		return m.CmdSeq
	}
	return 0
}

func (m *ProtocolMessage) GetCmdData() []byte {
	if m != nil {
		return m.CmdData
	}
	return nil
}

type RPCRequestPacket struct {
	IsOneWay             bool              `protobuf:"varint,1,opt,name=IsOneWay,proto3" json:"IsOneWay,omitempty"`
	RequestId            uint32            `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ServiceName          string            `protobuf:"bytes,3,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	FuncName             string            `protobuf:"bytes,4,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	ReqPayload           []byte            `protobuf:"bytes,5,opt,name=ReqPayload,proto3" json:"ReqPayload,omitempty"`
	Timeout              uint32            `protobuf:"varint,6,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Context              map[string]string `protobuf:"bytes,7,rep,name=Context,proto3" json:"Context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RPCRequestPacket) Reset()         { *m = RPCRequestPacket{} }
func (m *RPCRequestPacket) String() string { return proto.CompactTextString(m) }
func (*RPCRequestPacket) ProtoMessage()    {}
func (*RPCRequestPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RPCRequestPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequestPacket.Unmarshal(m, b)
}
func (m *RPCRequestPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequestPacket.Marshal(b, m, deterministic)
}
func (m *RPCRequestPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequestPacket.Merge(m, src)
}
func (m *RPCRequestPacket) XXX_Size() int {
	return xxx_messageInfo_RPCRequestPacket.Size(m)
}
func (m *RPCRequestPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequestPacket.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequestPacket proto.InternalMessageInfo

func (m *RPCRequestPacket) GetIsOneWay() bool {
	if m != nil {
		return m.IsOneWay
	}
	return false
}

func (m *RPCRequestPacket) GetRequestId() uint32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *RPCRequestPacket) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RPCRequestPacket) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *RPCRequestPacket) GetReqPayload() []byte {
	if m != nil {
		return m.ReqPayload
	}
	return nil
}

func (m *RPCRequestPacket) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RPCRequestPacket) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

type RPCResponsePacket struct {
	RPCRetCode           int32             `protobuf:"varint,1,opt,name=RPCRetCode,proto3" json:"RPCRetCode,omitempty"`
	RequestId            uint32            `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	RspPayload           []byte            `protobuf:"bytes,3,opt,name=RspPayload,proto3" json:"RspPayload,omitempty"`
	Context              map[string]string `protobuf:"bytes,4,rep,name=Context,proto3" json:"Context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RPCResponsePacket) Reset()         { *m = RPCResponsePacket{} }
func (m *RPCResponsePacket) String() string { return proto.CompactTextString(m) }
func (*RPCResponsePacket) ProtoMessage()    {}
func (*RPCResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *RPCResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCResponsePacket.Unmarshal(m, b)
}
func (m *RPCResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCResponsePacket.Marshal(b, m, deterministic)
}
func (m *RPCResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCResponsePacket.Merge(m, src)
}
func (m *RPCResponsePacket) XXX_Size() int {
	return xxx_messageInfo_RPCResponsePacket.Size(m)
}
func (m *RPCResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_RPCResponsePacket proto.InternalMessageInfo

func (m *RPCResponsePacket) GetRPCRetCode() int32 {
	if m != nil {
		return m.RPCRetCode
	}
	return 0
}

func (m *RPCResponsePacket) GetRequestId() uint32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *RPCResponsePacket) GetRspPayload() []byte {
	if m != nil {
		return m.RspPayload
	}
	return nil
}

func (m *RPCResponsePacket) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtocolMessage)(nil), "gpbrpc.ProtocolMessage")
	proto.RegisterType((*RPCRequestPacket)(nil), "gpbrpc.RPCRequestPacket")
	proto.RegisterMapType((map[string]string)(nil), "gpbrpc.RPCRequestPacket.ContextEntry")
	proto.RegisterType((*RPCResponsePacket)(nil), "gpbrpc.RPCResponsePacket")
	proto.RegisterMapType((map[string]string)(nil), "gpbrpc.RPCResponsePacket.ContextEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xd3, 0xa6, 0xcd, 0xb4, 0xc5, 0xba, 0x88, 0x84, 0x22, 0x12, 0x0a, 0x4a, 0x4f,
	0x39, 0xe8, 0x45, 0x7a, 0x51, 0x88, 0x0a, 0x3d, 0xa8, 0x61, 0x2b, 0x88, 0xc7, 0x6d, 0x32, 0x94,
	0xd2, 0x26, 0x9b, 0x66, 0x37, 0xc5, 0x3e, 0x9e, 0x4f, 0xe4, 0x2b, 0xc8, 0x6e, 0x92, 0x36, 0x7a,
	0xf1, 0xe2, 0x2d, 0xff, 0x3f, 0xb3, 0x33, 0xf3, 0xfd, 0x04, 0xfa, 0x31, 0x0a, 0xc1, 0x16, 0xe8,
	0xa5, 0x19, 0x97, 0x9c, 0x58, 0x8b, 0x74, 0x9e, 0xa5, 0xe1, 0xe8, 0x1d, 0x8e, 0x02, 0x65, 0x84,
	0x7c, 0xfd, 0x54, 0x34, 0x90, 0x13, 0x68, 0xf9, 0x71, 0x34, 0x8d, 0x1c, 0xc3, 0x35, 0xc6, 0x4d,
	0x5a, 0x08, 0x72, 0x0a, 0x96, 0x1f, 0x47, 0x33, 0xdc, 0x38, 0x0d, 0x6d, 0x97, 0x8a, 0x38, 0xd0,
	0xf6, 0xe3, 0xe8, 0x9e, 0x49, 0xe6, 0x98, 0xae, 0x31, 0xee, 0xd1, 0x4a, 0x8e, 0x3e, 0x1b, 0x30,
	0xa0, 0x81, 0x4f, 0x71, 0x93, 0xa3, 0x90, 0x01, 0x0b, 0x57, 0x28, 0xc9, 0x10, 0x3a, 0x53, 0xf1,
	0x92, 0xe0, 0x1b, 0xdb, 0xe9, 0xf9, 0x1d, 0xba, 0xd7, 0xe4, 0x0c, 0xec, 0xb2, 0x79, 0x1a, 0xe9,
	0x2d, 0x7d, 0x7a, 0x30, 0x88, 0x0b, 0xdd, 0x19, 0x66, 0xdb, 0x65, 0x88, 0xcf, 0x2c, 0x46, 0xbd,
	0xcc, 0xa6, 0x75, 0x4b, 0xcd, 0x7e, 0xcc, 0x93, 0x50, 0x97, 0x9b, 0xba, 0xbc, 0xd7, 0xe4, 0x1c,
	0x80, 0xe2, 0x26, 0x60, 0xbb, 0x35, 0x67, 0x91, 0xd3, 0xd2, 0x97, 0xd6, 0x1c, 0x85, 0xf1, 0xba,
	0x8c, 0x91, 0xe7, 0xd2, 0xb1, 0xf4, 0xe6, 0x4a, 0x92, 0x5b, 0x68, 0xfb, 0x3c, 0x91, 0xf8, 0x21,
	0x9d, 0xb6, 0x6b, 0x8e, 0xbb, 0x57, 0x17, 0x5e, 0x91, 0x9d, 0xf7, 0x1b, 0xce, 0x2b, 0xfb, 0x1e,
	0x12, 0x99, 0xed, 0x68, 0xf5, 0x6a, 0x38, 0x81, 0x5e, 0xbd, 0x40, 0x06, 0x60, 0xae, 0xb0, 0xa0,
	0xb7, 0xa9, 0xfa, 0x54, 0x89, 0x6f, 0xd9, 0x3a, 0x47, 0x0d, 0x6d, 0xd3, 0x42, 0x4c, 0x1a, 0x37,
	0xc6, 0xe8, 0xcb, 0x80, 0x63, 0xbd, 0x46, 0xa4, 0x3c, 0x11, 0x58, 0x86, 0xa8, 0x60, 0x94, 0x29,
	0x7d, 0x1e, 0xa1, 0x1e, 0xd4, 0xa2, 0x35, 0xe7, 0x8f, 0x20, 0xd5, 0x6b, 0x91, 0x56, 0x51, 0x98,
	0x65, 0x14, 0x7b, 0x87, 0xdc, 0x1d, 0x80, 0x9b, 0x1a, 0xf8, 0xf2, 0x07, 0x70, 0xfd, 0x92, 0xff,
	0x27, 0x9e, 0x5b, 0xfa, 0xff, 0xbc, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe0, 0x8a, 0x6f,
	0xb0, 0x02, 0x00, 0x00,
}
